### ISSUE TITLE
Update msw

### ISSUE THREAD

**Issue by rmalca** [warrenday/graphql-mock-network#3]
I get this error in msw 0.21.3 using cypress-graphql-mock-network 0.2.2 in Chrome browser v87:

```
[MSW] Failed to execute setupServer in the environment that is not NodeJS (i.e. a browser). Consider using setupWorker instead.
```

This line triggers the error:
```
cy.mockNetwork({ schema })
```

I used npm shrinkwrap to update to msw 0.25 and the problem is fixed.

**Comment by warrenday** [comment]
Update now available with updated MSW
