### ISSUE TITLE
Expose Resolvers

### ISSUE THREAD

**Issue by oririner-wiz** [warrenday/graphql-mock-network#5]
The `@graphql-tools/mock` library allows us to [supply custom resolvers](https://www.graphql-tools.com/docs/mocking/#applying-mutations)

This comes in handy when you want to supply custom mock data depending on the input (because mocks don't get the query/mutation variables).

All that's needed to to allow us to pass in the resolvers function/object, not just the mocks object.
Alternatively, since there's already a custom `handleRequest` function that has access to the variables, it can be passed down to the mocks without having to work with custom resolvers/mock store.

Also, I'm using this repo through [`cypress-graphql-mock-network`](https://github.com/warrenday/cypress-graphql-mock-network) so it needs to be supported there as well :)

Anyway, thanks for all your work on this 🙏 Super helpful!

**Comment by oririner-wiz** [comment]
Hey @warrenday any chance on doing it? I'd be willing to contribute it myself if needed :)

**Comment by warrenday** [comment]
Hey @oririner-wiz could you provide a code example of what you are explaining? Is the issue that the mock resolver are not receiving query variables?

**Comment by warrenday** [comment]
Ok I've read through the docs you linked and understand the issue more now.

I hadn't realised there was such a breaking change so that mock functions do not receive the context and argument values.

If you wanted to help on this one that would be great. 

What are your thoughts on how the API for this would look? Should we handle the changes internally and keep the API the same, or add new public methods/arguments for dealing with resolvers separately?

**Comment by oririner-wiz** [comment]
Hey @warrenday 

It's actually a bit more difficult than I initially thought. Since mocks behave differently than resolvers, mocks can be partial and resolvers can't you'd need to go through a lot of hoops to get the resolvers to do what you want.

Trying to handle this change internally only through mocks will probably result in different response of the mocks causing a breaking change in functionality which is somewhat worse (the API is the same so users think it's OK, but in reality the graphql responses are different).

One thing you'd have to define a [`mockStore`](https://www.graphql-tools.com/docs/api/classes/mock_src.mockstore) and in the resolvers themselves use that store to provide a mocked value.

Luckily, resolvers can actually be a function getting the store and returns the actual resolvers.

So, I think the best way to approach this is to provide the resolvers as-is to the mocked schema and let the user define whatever they need there as well as keeping the mocks the way they are right now.

Also, I [created a ticket to bring back the access to the input variables in mocks](https://github.com/ardatan/graphql-tools/issues/3209) since it's not technically the same to use resolvers and mock store.

**Comment by warrenday** [comment]
Awesome thanks for raising that. I'll keep an eye on progress. In the meantime I'll expose resolvers directly so developers have some sort of workable solution to dynamic mocking.

**Comment by rodrigo-roamdigital** [comment]
@warrenday any news about this one?, it'd be nice to have some resolvers for dynamic mocking 🙌

**Comment by warrenday** [comment]
I've not managed to look into this yet. But the latest version of GraphQL tools basically makes it impossible without a hack.

It would seem hard to fix without a change on their side.

Earlier versions of this lib, for example 0.3.0 do allow access to 'args' as it uses an earlier version of GraphQL tools.

If you can get away with using that it would help for now.

**Comment by warrenday** [comment]
@rodrigo-roamdigital args are now available again in the latest release. They are available as the first argument on a mock function.

```
user: (args) => {}
```

I'll close this now as I think this solves your problem.
